### ISSUE TITLE
Index cache hit ratio

### ISSUE THREAD

**Issue by Mochizuki-S2** [pg-monz/pg_monz#16]
Hi.

Is this correct in pgsql_tbl_funcs.sh:27 ?

> ... idx_blks_hit * 100 / (idx_blks_hit + heap_blks_read + 0.0001) ...

https://github.com/pg-monz/pg_monz/blob/master/pg_monz/usr-local-bin/pgsql_tbl_funcs.sh#L27

I think to use not "heap_blks_read" but "idx_blks_read" .

**Comment by shimogai** [comment]
Thank you for pointing it out.
I corrected the formula to use "idx_blks_read".

**Comment by Mochizuki-S2** [comment]
Nice work !:+1:
