### ISSUE TITLE
I can't monitor PostgreSQL process(when use rhel6 PGDG package) 

### ISSUE THREAD

**Issue by Mochizuki-S2** [pg-monz/pg_monz#17]
Hi.

I use [rhel6 PGDG postgres package](http://yum.postgresql.org/repopackages.php).

>  # rpm -ivh http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-redhat94-9.4-2.noarch.rpm
>  # yum install postgresql94-server

PGDG init.d scripit use [postmaster](http://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/9.5/postgresql/EL-6/postgresql.init;h=12ce400a22b7f3f08e708c8c19069b91bf488e4a;hb=HEAD#l163)( [deprecated....](http://www.postgresql.org/docs/9.4/static/app-postmaster.html) ) when we start service.

>  # service postgresql-9.4 start
>  # ps -ef | grep postmaster

But pg_monz monitor only ["postgres" process](https://github.com/pg-monz/pg_monz/blob/04d3c007cfcb083caedb1ff9b6043ab511c85151/pg_monz/template/Template_App_PostgreSQL.xml#L640).

So, I can't monitor PostgreSQL process with pg_monz.

**Comment by kumor** [comment]
Change the key for the "Number of postgres process" in the "Template App PostgreSQL" template from proc.num[postgres,,,] to **proc.num[postmaster,,,]**

**Comment by Mochizuki-S2** [comment]
Thanks! That went will.

I tried to monitor 'postgres' or 'postmaster' process (like proc.num[postgres|postmaster,,,]), but  couldn't do it.
It looks like to need complex changes if I achive it.
