### ISSUE TITLE
pgsql_primary.sh and pgsql_standby.sh, wrong variable

### ISSUE THREAD

**Issue by hallamigo** [pg-monz/pg_monz#23]
In the "**pgsql_primary.sh**" and "**pgsql_standby.sh**" files it has **$DBNAME** and it should probably be **$PGDATABASE**, which is what is found in the "**/usr/local/etc/pgsql_funcs.conf**" file.  It erred for me until I changed it.

**Comment by michaelwemoto** [comment]
This also affects pgsql_simple.sh

**Comment by y-hiroyu** [comment]
Fixed at 2.0.1 release. Thanks!
