### ISSUE TITLE
zabbix trapper items are not gathering values 

### ISSUE THREAD

**Issue by Divyavi** [pg-monz/pg_monz#49]
I have this issue with my zabbix 4. pgsql 11 and Rhel 7. Trappers are unable to gather values from local host. (DB and Server on same host installation) If I push values using sender they are getting updated but its not happening automatically. What could be wrong

**Comment by pengbo0328** [comment]
I think the config in "/usr/local/etc/pgsql_funcs.conf" is not correct.
You have to make sure you can connect PostgreSQL with the "PGHOST", "PGPORT" ,"PGROLE"  and "PGDATABASE" which you configured in "/usr/local/etc/pgsql_funcs.conf".

Try if you can connect PostgreSQL by using
psql -h "PGHOST" -p "PGPORT"  -U "PGROLE"  "PGDATABASE"

**Comment by Divyavi** [comment]
Issue was that the trapper was not in its default location and hence this was not working. I added the path into each of the scripts and that got it working.

Thank you for this Add-On

Regards,
Avi
