### ISSUE TITLE
Support for PGSSLMODE in pg_monz .conf file

### ISSUE THREAD

**Issue by pr2git** [pg-monz/pg_monz#59]
Hi,

My company strategy is to disallow the SSL connection locally (127.0.0.1) from the pg_hba.conf.
But by default every psql cmd line query is first trying a SSL connection then fallback to no encryption. This lead into a log pollution on the postgres.log and useless double query.

There is a solution for it, it is to implement the PGSSLMODE, so I would like to be able to use this in my pgsql_funcs.conf.

PGSSLMODE="disable"

https://www.postgresql.org/docs/9.0/libpq-envars.html

But, of course, this implies to have this parameter added to all psql cmd call into pg_monz.

Do you think possible to implement it?

Or may be a more generic approach for people willing to pass custom parameters.
A kind of:  PGMZOPTIONS="PGSSLMODE=\"disable\""

Thanks

**Comment by pengbo0328** [comment]
Yes. I think adding custom parameters in "pgsql_funcs.conf" will be more useful.

**Comment by pengbo0328** [comment]
> My company strategy is to disallow the SSL connection locally (127.0.0.1) from the pg_hba.conf.

The workaround is that you can specify the IP address or hostname in "PGHOST=xxxxxx".

**Comment by pr2git** [comment]
> > My company strategy is to disallow the SSL connection locally (127.0.0.1) from the pg_hba.conf.
> 
> The workaround is that you can specify the IP address or hostname in "PGHOST=xxxxxx".

This is not a work around sine I already use the PGHOST parameter and SSL is enabled.
The work around in my case would be to use the Unix socket instead of the TCP connexion but PGHOST is a mandatory parameter since it is the parameter passed to -h option on every psql call.
If you drop the -h option then it will use Unix socket, but this not foreseen neither.

Here is a manual simulation if you don't define PGHOST:

psql -h -U postgres -d postgres -c "SELECT 1"
psql: could not translate host name "-U" to address: node name or service name not known

Then I need to specify PGHOST then I have

psql -h 127.0.0.1 -U postgres -d postgres -c "SELECT 1"
 ?column? 
----------
        1
(1 row)

(or localhost of course) and in the postgres log:

postgres postgres LOG:  connection authorized: user=postgres database=postgres **SSL enabled**

But if I performed the same command without the -h

psql -U postgres -d postgres -c "SELECT 1"
 ?column? 
----------
        1
(1 row)


Then in the log;

postgres postgres LOG:  connection authorized: user=postgres database=postgres

And no SSL.

So the fact to force to use the PGHOST trigger the TCP connection and by default psql first try SSL and then fallback into no SSL connection when it is forbidden but this generate tons of entries in the log.

So another work-around is to test if PGHOST is empty and then call all the psql statement without the -h parameter.
