### ISSUE TITLE
support windows server?

### ISSUE THREAD

**Issue by yasu47b** [pg-monz/pg_monz#61]
Hello.

Is this Library support PostgreSQL on Windows Server?

I looked files on repository and thought it for Linux or Unix.
I also googled a lot but I couldn't get any info about it.

Thanks

**Comment by pengbo0328** [comment]
No. pg_monz doesn't support windows server.

**Comment by yasu47b** [comment]
@pengbo0328  Thanks a reply.

I'll close this issue.
