### ISSUE TITLE
Configuration Error: "db.list.discovery" already exists

### ISSUE THREAD

**Issue by MichaelDBA** [pg-monz/pg_monz#66]
After I followed all the instructions to install and configure pg_monz, I get this error when trying to restart the zabbix-agent.
`zabbix_agentd[7805]: zabbix_agentd [7805]: ERROR: cannot add user parameter "db.list.discovery[*],"$1"/find_dbname.sh "$2"": key "db.list.discovery" already exists`

I am using Zabbix 5.2 and PostgreSQL 13 on CentOS 8.

I am just trying to test out the postgresql plugin on the zabbix server before pushing it out to other hosts.

If I update /etc/zabbix/zabbix_agentd.conf and comment out this:
#Include=/etc/zabbix/zabbix_agentd.d/*.conf

and then uncomment this:
#works for pg_monz plugin
Include=/etc/zabbix/zabbix_agentd.d/userparameter_pgsql.conf

I have these files in /etc/zabbix/zabbix_agentd.d folder:
template_db_postgresql.conf
userparameter_pgsql.conf
zabbix-extensions.conf

Then zabbix agent restarts OK, but then I cannot access this stuff from webconsole dashboard.

**Comment by pengbo0328** [comment]
> key "db.list.discovery" already exists

It seems that the key "db.list.discovery" has already been configured in zabbix_agentd.conf or in one of the config files under zabbix_agentd.d directory.

If you include config files like below, "db.list.discovery" may be configured multiple times.
```
Include=/etc/zabbix/zabbix_agentd.d/*.conf
Include=/etc/zabbix/zabbix_agentd.d/userparameter_pgsql.conf
```
I think you need to change
```
Include=/etc/zabbix/zabbix_agentd.d/*.conf
Include=/etc/zabbix/zabbix_agentd.d/userparameter_pgsql.conf
```
to 
```
Include=/etc/zabbix/zabbix_agentd.d/*.conf
```

**Comment by pengbo0328** [comment]
pg_monz doesn't support Zabbix 5.0 or later. It may not work with Zabbix 5.0.

**Comment by MichaelDBA** [comment]
oh no!  Are there any plans to upgrade this tool for v5?

**Comment by pengbo0328** [comment]
No. We don't have plan to support Zabbix 5.0 or later.
It is recommended to use the standard template "Template DB PostgreSQL" for monitoring PostgreSQL in Zabbix 5.0 or later.
